export const mockClouds: ICloudComment[] = [
  {
    id: 1,
    content: '구름 1',
    createAt: new Date(),
    displayTime: 0,
    displayHeight: 50,
    displaySize: 20,
    speed: 'medium',
  },
  {
    id: 2,
    content: '구름 2',
    createAt: new Date(),
    displayTime: 10,
    displayHeight: 80,
    displaySize: 20,
    speed: 'medium',
  },
  {
    id: 3,
    content: 'ㅎㅇㅎㅇ 🐬🐬🐬',
    createAt: new Date(),
    displayTime: 6,
    displayHeight: 60,
    displaySize: 24,
    speed: 'medium',
  },
  {
    id: 4,
    content: '안녕하세요',
    createAt: new Date(),
    displayTime: 3,
    displayHeight: 80,
    displaySize: 16,
    speed: 'medium',
  },
  {
    id: 5,
    content: '안녕하세요',
    createAt: new Date(),
    displayTime: 3.2,
    displayHeight: 80,
    displaySize: 16,
    speed: 'medium',
  },
  {
    id: 6,
    content: '안녕하세요',
    createAt: new Date(),
    displayTime: 3.4,
    displayHeight: 80,
    displaySize: 20,
    speed: 'medium',
  },
];
