export const mockClouds: ICloudComment[] = [
  {
    id: '1',
    videoTitle: '',
    nickname: '3145',
    content: '구름 1',
    createdAt: new Date().toISOString(),
    displayTime: 0,
    displayHeight: 50,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
  {
    id: '2',
    videoTitle: '',
    nickname: '3145',
    content: '구름 2',
    createdAt: new Date().toISOString(),
    displayTime: 10,
    displayHeight: 80,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
  {
    id: '3',
    videoTitle: '',
    nickname: '3145',
    content: 'ㅎㅇㅎㅇ 🐬🐬🐬',
    createdAt: new Date().toISOString(),
    displayTime: 6,
    displayHeight: 60,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
  {
    id: '4',
    videoTitle: '',
    nickname: '3145',
    content: '안녕하세요',
    createdAt: new Date().toISOString(),
    displayTime: 3,
    displayHeight: 80,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
  {
    id: '5',
    videoTitle: '',
    nickname: '3145',
    content: '안녕하세요',
    createdAt: new Date().toISOString(),
    displayTime: 3.2,
    displayHeight: 80,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
  {
    id: '6',
    videoTitle: '',
    nickname: '3145',
    content: '안녕하세요',
    createdAt: new Date().toISOString(),
    displayTime: 3.4,
    displayHeight: 80,
    displaySize: 'medium',
    displaySpeed: 'medium',
  },
];
